# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8aec65d8ee68d0d48eaad52f50a4d56292a6ca9a1557697d536b74c1abcd1c2923cc8f52c11fc299a17227a340bd4f129073bb9d4ae9472ceb3deab9e4acf58

test:
  secret_key_base: 2a697d014855028eb7968145a48714c8ea413015e2238e2cb2b05d146af78ab1a8ca727e4148c45e95c67c06cd44a1f6c82e49eb746185968746e3f01c63e3de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
